"""
Seeded infrastructure assets for SANKET CivicLens Civic DNA intelligence layer.
"""

from typing import List, Dict, Any

SEED_ASSETS: List[Dict[str, Any]] = [
    {
        "id": "S35-L092",
        "assetNumber": "S35-L092",
        "assetType": "streetlight",
        "name": "High-Mast Luminaire #S35-L092",
        "location": "Jan Marg Intersection, Sector 35-D",
        "sector": "Sector 35",
        "latitude": 30.7189,
        "longitude": 76.7563,
        "department": "Street Lighting Department",
        "installationDate": "2019-03-15",
        "installationYear": 2019,
        "ageYears": 7,
        "currentStatus": "needs_attention",
        "currentRiskScore": 73,
        "currentHealthScore": 61,
        "totalComplaints": 8,
        "totalRepairs": 4,
        "failureCount": 4,
        "recurrenceCount": 3,
        "lastRepairDate": "2025-07-14",
        "lastInspectionDate": "2026-02-10",
        "estimatedLifetimeYears": 12,
        "actualLifetimeYears": 7,
        "totalMaintenanceCost": 19700.0,
        "estimatedReplacementCost": 11000.0,
        "potentialSavings": 7700.0,
        "currentComponent": "LED driver (150W IP66)",
        "associatedIncidentIds": ["inc-003"],
        "events": [
            {
                "id": "ev-3501",
                "assetId": "S35-L092",
                "eventType": "installation",
                "date": "2019-03-15",
                "year": 2019,
                "title": "Asset Commissioning & Energization",
                "description": "High-mast 150W LED pole installed along Jan Marg arterial corridor. Subgrade grounding certified.",
                "department": "Street Lighting Department",
                "cost": 0,
                "contractor": "Havells Urban Infrastructure"
            },
            {
                "id": "ev-3502",
                "assetId": "S35-L092",
                "eventType": "complaint",
                "date": "2021-02-18",
                "year": 2021,
                "title": "Complaint #C1042 — Streetlight Not Functioning",
                "description": "Citizen report: Pedestrian crossing unlit after thunderstorm. Voltage fluctuation reported.",
                "department": "Street Lighting Department",
                "cost": 0,
                "complaintId": "C1042"
            },
            {
                "id": "ev-3503",
                "assetId": "S35-L092",
                "eventType": "repair",
                "date": "2022-01-10",
                "year": 2022,
                "title": "Repair Completed — LED Driver Replacement",
                "description": "Burned out driver replaced with standard 150W unit. Wiring continuity tested.",
                "department": "Street Lighting Department",
                "cost": 3800,
                "contractor": "MC Electrical Division II"
            },
            {
                "id": "ev-3504",
                "assetId": "S35-L092",
                "eventType": "failure",
                "date": "2024-07-22",
                "year": 2024,
                "title": "Repeated Outage — Second Driver Failure",
                "description": "Substation phase surge triggered thermal cutoff in driver circuit. Lamp intermittent.",
                "department": "Street Lighting Department",
                "cost": 0,
                "metadata": {"component": "LED driver (150W IP66)"}
            },
            {
                "id": "ev-3505",
                "assetId": "S35-L092",
                "eventType": "component_replacement",
                "date": "2024-08-05",
                "year": 2024,
                "title": "Component Replaced — Second LED Driver Swap",
                "description": "Driver unit swapped out again. External surge arrestor not fitted due to inventory shortage.",
                "department": "Street Lighting Department",
                "cost": 4200,
                "contractor": "MC Electrical Division II"
            },
            {
                "id": "ev-3506",
                "assetId": "S35-L092",
                "eventType": "complaint",
                "date": "2025-05-19",
                "year": 2025,
                "title": "Complaint #C4821 — Dark Spot Near Bus Stop",
                "description": "Night safety issue flagged by RWA Sector 35. High pedestrian volume corridor.",
                "department": "Street Lighting Department",
                "cost": 0,
                "complaintId": "C4821"
            },
            {
                "id": "ev-3507",
                "assetId": "S35-L092",
                "eventType": "repair",
                "date": "2025-07-14",
                "year": 2025,
                "title": "Emergency Repair — Third Driver Replaced",
                "description": "Driver replaced with patch unit. Ground insulation resistance measured at marginal 1.2 MΩ.",
                "department": "Street Lighting Department",
                "cost": 4500,
                "contractor": "Suraksha Electricals"
            },
            {
                "id": "ev-3508",
                "assetId": "S35-L092",
                "eventType": "inspection",
                "date": "2026-02-10",
                "year": 2026,
                "title": "Annual Municipal Infrastructure Audit",
                "description": "Audit flagged accelerated failure rhythm. Luminaire housing shows seal degradation and moisture ingress.",
                "department": "Street Lighting Department",
                "cost": 7200,
                "contractor": "MC Quality Assurance Cell"
            },
            {
                "id": "ev-3509",
                "assetId": "S35-L092",
                "eventType": "prediction",
                "date": "2026-03-01",
                "year": 2026,
                "title": "SANKET Predictive Notice — Imminent 5th Failure",
                "description": "Failure acceleration model projects next outage within 90 days if driver is not permanently upgraded.",
                "department": "Street Lighting Department",
                "cost": 0
            }
        ]
    },
    {
        "id": "RD17-P001",
        "assetNumber": "RD17-P001",
        "assetType": "road_segment",
        "name": "Madhya Marg Subgrade Section #RD17-P001",
        "location": "Madhya Marg Corridor, Sector 17-C",
        "sector": "Sector 17",
        "latitude": 30.7380,
        "longitude": 76.7820,
        "department": "Roads & Infrastructure",
        "installationDate": "2018-11-20",
        "installationYear": 2018,
        "ageYears": 8,
        "currentStatus": "critical",
        "currentRiskScore": 81,
        "currentHealthScore": 48,
        "totalComplaints": 14,
        "totalRepairs": 5,
        "failureCount": 5,
        "recurrenceCount": 4,
        "lastRepairDate": "2025-09-02",
        "lastInspectionDate": "2026-01-18",
        "estimatedLifetimeYears": 10,
        "actualLifetimeYears": 8,
        "totalMaintenanceCost": 240000.0,
        "estimatedReplacementCost": 180000.0,
        "potentialSavings": 95000.0,
        "currentComponent": "Bituminous wearing course & sub-base",
        "associatedIncidentIds": ["inc-001"],
        "events": [
            {
                "id": "ev-1701",
                "assetId": "RD17-P001",
                "eventType": "installation",
                "date": "2018-11-20",
                "year": 2018,
                "title": "Corridor Reconstruction & Resurfacing",
                "description": "Dense bituminous macadam 50mm overlay with stone mastic asphalt finish.",
                "department": "Roads & Infrastructure",
                "cost": 180000,
                "contractor": "National Paving Corp"
            },
            {
                "id": "ev-1702",
                "assetId": "RD17-P001",
                "eventType": "failure",
                "date": "2021-08-15",
                "year": 2021,
                "title": "Subgrade Shear Failure & Alligator Cracking",
                "description": "Severe rutting after monsoon saturation. Water trapped due to blocked side drain.",
                "department": "Roads & Infrastructure",
                "cost": 0,
                "metadata": {"component": "Subgrade drainage layer"}
            },
            {
                "id": "ev-1703",
                "assetId": "RD17-P001",
                "eventType": "repair",
                "date": "2021-10-04",
                "year": 2021,
                "title": "Cold-Mix Patchwork & Profiling",
                "description": "Patching executed over 40 sq meters. Structural sub-base not excavated.",
                "department": "Roads & Infrastructure",
                "cost": 45000,
                "contractor": "MC Road Div I"
            },
            {
                "id": "ev-1704",
                "assetId": "RD17-P001",
                "eventType": "failure",
                "date": "2023-07-28",
                "year": 2023,
                "title": "Patch Re-collapse & Severe Depression",
                "description": "Previous cold-mix patch washed out during heavy rainfall. Vehicle rim damage reported.",
                "department": "Roads & Infrastructure",
                "cost": 0,
                "metadata": {"component": "Subgrade drainage layer"}
            },
            {
                "id": "ev-1705",
                "assetId": "RD17-P001",
                "eventType": "repair",
                "date": "2023-09-12",
                "year": 2023,
                "title": "Hot-Mix Patchwork & Roller Compaction",
                "description": "Patch repeated with hot bituminous mix. Edge sealing applied.",
                "department": "Roads & Infrastructure",
                "cost": 65000,
                "contractor": "MC Road Div I"
            },
            {
                "id": "ev-1706",
                "assetId": "RD17-P001",
                "eventType": "failure",
                "date": "2025-08-10",
                "year": 2025,
                "title": "Alligator Cracking & Pothole Cluster",
                "description": "Deep alligator cracking spreading across 65 meters. Heavy transit bus axle load stress.",
                "department": "Roads & Infrastructure",
                "cost": 0,
                "metadata": {"component": "Subgrade drainage layer"}
            },
            {
                "id": "ev-1707",
                "assetId": "RD17-P001",
                "eventType": "repair",
                "date": "2025-09-02",
                "year": 2025,
                "title": "Interim Asphalt Leveling",
                "description": "Emergency leveling for festival traffic. Engineer noted sub-base failure.",
                "department": "Roads & Infrastructure",
                "cost": 130000,
                "contractor": "Shivalik Bitumen Co"
            }
        ]
    },
    {
        "id": "DR22-D002",
        "assetNumber": "DR22-D002",
        "assetType": "drainage",
        "name": "Box Culvert Stormwater Conduit #DR22-D002",
        "location": "Aroma Chowk Underpass, Sector 22-C",
        "sector": "Sector 22",
        "latitude": 30.7245,
        "longitude": 76.7680,
        "department": "Drainage & Sewerage",
        "installationDate": "2017-06-10",
        "installationYear": 2017,
        "ageYears": 9,
        "currentStatus": "needs_attention",
        "currentRiskScore": 76,
        "currentHealthScore": 54,
        "totalComplaints": 11,
        "totalRepairs": 4,
        "failureCount": 4,
        "recurrenceCount": 3,
        "lastRepairDate": "2025-08-20",
        "lastInspectionDate": "2026-01-12",
        "estimatedLifetimeYears": 20,
        "actualLifetimeYears": 9,
        "totalMaintenanceCost": 92000.0,
        "estimatedReplacementCost": 125000.0,
        "potentialSavings": 42000.0,
        "currentComponent": "Precast RCC baffle wall & grate",
        "associatedIncidentIds": ["inc-002"],
        "events": [
            {
                "id": "ev-2201",
                "assetId": "DR22-D002",
                "eventType": "installation",
                "date": "2017-06-10",
                "year": 2017,
                "title": "Storm Conduit Commissioned",
                "description": "Precast RCC box culvert connecting Sector 22 underpass to main stormwater nallah.",
                "department": "Drainage & Sewerage",
                "cost": 125000,
                "contractor": "Punjab Drainage Works"
            },
            {
                "id": "ev-2202",
                "assetId": "DR22-D002",
                "eventType": "failure",
                "date": "2022-07-15",
                "year": 2022,
                "title": "Grate Displacement & Heavy Silt Ingress",
                "description": "Monsoon surge displaced cast-iron grate; stormwater backflow flooded pedestrian tunnel.",
                "department": "Drainage & Sewerage",
                "cost": 0,
                "metadata": {"component": "Inlet grate"}
            },
            {
                "id": "ev-2203",
                "assetId": "DR22-D002",
                "eventType": "repair",
                "date": "2022-08-01",
                "year": 2022,
                "title": "De-silting & Grate Re-anchoring",
                "description": "Hydro-jet de-silting and chemical mortar anchor replacement.",
                "department": "Drainage & Sewerage",
                "cost": 22000,
                "contractor": "MC Drainage Wing"
            },
            {
                "id": "ev-2204",
                "assetId": "DR22-D002",
                "eventType": "failure",
                "date": "2024-07-09",
                "year": 2024,
                "title": "Repeated Baffle Wall Structural Fracture",
                "description": "Cracking along precast baffle joint. Debris clogging intake during pre-monsoon shower.",
                "department": "Drainage & Sewerage",
                "cost": 0,
                "metadata": {"component": "Baffle wall"}
            },
            {
                "id": "ev-2205",
                "assetId": "DR22-D002",
                "eventType": "repair",
                "date": "2024-08-04",
                "year": 2024,
                "title": "Baffle Epoxy Grouting & Clearing",
                "description": "Pressure grouting applied to fractured joint. Temporary intake screen added.",
                "department": "Drainage & Sewerage",
                "cost": 34000,
                "contractor": "MC Drainage Wing"
            },
            {
                "id": "ev-2206",
                "assetId": "DR22-D002",
                "eventType": "failure",
                "date": "2025-08-05",
                "year": 2025,
                "title": "Flash Flooding at Aroma Underpass",
                "description": "Water accumulated to 1.5 ft depth. Intake screen collapsed under silt load.",
                "department": "Drainage & Sewerage",
                "cost": 0,
                "metadata": {"component": "Baffle wall"}
            },
            {
                "id": "ev-2207",
                "assetId": "DR22-D002",
                "eventType": "repair",
                "date": "2025-08-20",
                "year": 2025,
                "title": "Emergency Mud Pumping & Temporary Grate",
                "description": "High-capacity diesel pumps deployed for 36 hours. Mild steel cage fabricated locally.",
                "department": "Drainage & Sewerage",
                "cost": 36000,
                "contractor": "QuickResponse Sanitation"
            }
        ]
    }
]
